### PR TITLE
chore: css cleanup

### PR DESCRIPTION
**Pull request by baadaa**
Hello! I stumbled upon your LinkedIn post about this project today, and thought I'd suggest a few simple visual style updates. Namely:

- Removing unused styles from `Home.module.css`
- Add `max-width` and center-align the `main` container
- Make small changes to colors and link style

Hope you don't mind, and keep up the great work!

### CODE REVIEW

**Comment by Apollorion** [comment]
🔥 Thanks for the contribution, I'm absolutely not a visual expert so any help here is appreciated!

If you want, I've noticed the site is unusable on mobile. For some reason you cant scroll left or right and the text is all cut off. Would love some help remediating this. If not all good 😄

**Comment by baadaa** [comment]
Hey no problem. I did notice the mobile usability concerns but didn't want to impose too much change on your project. I could take a stab at addressing that, and suggest a few other visual niceties along with it.

**Comment by Apollorion** [comment]
> Hey no problem. I did notice the mobile usability concerns but didn't want to impose too much change on your project. I could take a stab at addressing that, and suggest a few other visual niceties along with it.

You wont offend me at all, thanks for the help! 😄

**Comment by baadaa** [comment]
I spend a couple of hours working on layout and other visual style changes. I didn't touch any app logic, but got a little carried away with some changes which might potentially cause merge conflicts (e.g. external CSS files, etc). Let me give you a preview in a bit. Please don't worry. I won't break anything for you.

**Pull request merged**
